name: Deploy to AWS/EC2

on:
  workflow_call:
    inputs:
      potpourri_target:
        description: The Potpourri target to run
        required: false
        default: ci/docker-app
        type: string
      base_path:
        description: The path to run all commands in, relative to the
          repository root
        required: false
        default: .
        type: string
      force_env:
        description: When given it overwrites the Potpourri configured
          `DEPLOY_ENV` environment variable
        required: false
        type: string
      timeout_minutes:
        description: Maximum time in minutes the workflow is allowed to run
        required: false
        default: 20
        type: number
      build_docs:
        description: Try to build the docs on production builds, or not
        required: false
        default: true
        type: boolean

jobs:
  deploy:
    name: EC2
    runs-on: ubuntu-22.04
    timeout-minutes: '${{ inputs.timeout_minutes }}'
    steps:
      - name: Prepare the environment
        uses: hausgold/actions/ci@v2
        with:
          clone_token: '${{ secrets.CLONE_TOKEN }}'
          settings_secret_key: '${{ secrets.SETTINGS_SECRET_KEY }}'
          settings: '${{ github.repository }}'
          target: '${{ inputs.potpourri_target }}'

      - name: Force deploy environment
        run:
          var ORIG_DEPLOY_ENV ${DEPLOY_ENV};
          var DEPLOY_ENV '${{ inputs.force_env }}'
        if: inputs.force_env != null

      - name: Deploy the application
        run: ec2-deployment deploy
        working-directory: '${{ inputs.base_path }}'

      - name: Run always post-deployment hooks
        run: ec2-deployment always-post-deploy-hooks
        working-directory: '${{ inputs.base_path }}'
        if: always()

      - name: Restore deploy environment
        run: var DEPLOY_ENV ${ORIG_DEPLOY_ENV}
        if: inputs.force_env != null

      - name: Write a message to Slack
        run: slack

      - name: Create a Github Deployment
        run: deployment

      - name: Build and upload application documentation
        run: api-docs && coverage --docs-only
        if: inputs.build_docs == true && env.DEPLOY_ENV == 'production'
        env:
          WORKFLOW_DISPATCH_TOKEN: '${{ secrets.WORKFLOW_DISPATCH_TOKEN }}'
