name: Package Container Image

on:
  workflow_call:
    inputs:
      # We focus on application which uses the shared
      # container image by default
      base_path:
        description: The container image build path, relative to the
          repository root
        required: false
        default: config/container
        type: string
      publish:
        description: Whenever to publish the image (AWS)
        required: false
        default: true
        type: boolean
      publish_prebuilt:
        description: Whenever to publish a prebuilt image (Docker Hub)
        required: false
        default: true
        type: boolean
      timeout-minutes:
        description: The maximum of time the package job may run
        required: false
        default: 15
        type: number

jobs:
  package:
    name: Container Image
    runs-on: ubuntu-22.04
    timeout-minutes: '${{ inputs.timeout-minutes }}'
    steps:
      - name: Prepare the environment
        uses: hausgold/actions/ci@v2
        with:
          clone_token: '${{ secrets.CLONE_TOKEN }}'
          settings_secret_key: '${{ secrets.SETTINGS_SECRET_KEY }}'
          settings: '${{ github.repository }}'
          target: ci/docker-app

      - name: Build the container image
        run: make build
        working-directory: '${{ inputs.base_path }}'

      - name: Run the container image test suite
        run: make test
        working-directory: '${{ inputs.base_path }}'

      - name: Upload the container image (AWS)
        if: inputs.publish == true
        run: make publish
        working-directory: '${{ inputs.base_path }}'

      - name: Upload the container image (Docker Hub)
        if: inputs.publish_prebuilt == true
        run: make publish-prebuilt
        working-directory: '${{ inputs.base_path }}'
