name: Doing chores (cleanups, etc)

on:
  workflow_call: {}

jobs:
  draft_release:
    name: Draft Release
    uses: hausgold/actions/.github/workflows/common-release-drafter.yml@v2
    secrets: inherit
    if: github.event_name != 'pull_request' &&
      (github.ref == 'refs/heads/master' || github.event_name == 'release')

  cleanup_deployment:
    name: Cleanup Deployment
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Prepare the environment
        uses: hausgold/actions/ci@v2
        with:
          clone_token: '${{ secrets.CLONE_TOKEN }}'
          settings_secret_key: '${{ secrets.SETTINGS_SECRET_KEY }}'
          settings: '${{ github.repository }}'
          target: '${{ inputs.potpourri_target }}'

      - name: Reconfigure the pull request/branch details
        run:
          var GITHUB_BRANCH '${{ github.head_ref }}';
          var GITHUB_PULL_REQUEST '${{ github.event.number }}'

      - name: Remove the Github Deployment of the feature branch
        run: deployment --remove

      - name: Remove S3 bucket of the feature branch
        run: s3-deployment clean
